# version: '3.8'

services:
  snort:
    build: 
      context: ./snort
      dockerfile: Dockerfile
    container_name: snort
    privileged: true
    volumes:
      - ./snort/host-volume:/usr/local/snort/etc/snort/docker-volume:ro #rules 
    networks:
      - private_network
    stdin_open: true

  attacker:
    build:
       context: ./attacker
       dockerfile: Dockerfile
    container_name: Mallory
    networks:
      - private_network
    tty: true
    stdin_open: true

  web:
    image: bkimminich/juice-shop
    container_name: juice
    networks:
      - private_network
    ports:
      - 80:80
    volumes:
      - ./web/default.yml:/juice-shop/config/myConfig.yml
    restart: always
    environment:
      PORT: "80"

networks:
  private_network:
    driver: bridge


