version: '3.8'

services:
  snort:
    image: snort3ml
    container_name: snort3ml
    volumes:
      - ./snort/host-volume:/usr/local/snort/etc/snort/docker-volume:ro
    networks:
      - private_network
    stdin_open: true

  kali:
    image: kalilinux/kali-rolling
    container_name: kali
    networks:
      - private_network
    tty: true
    stdin_open: true

networks:
  private_network:
    driver: bridge


