version: '3.8'

services:
  snort:
    image: localhost/snort3ml
    container_name: snort3ml
    volumes:
      - snort_data:/etc/snort
    networks:
      - private_network

  kali:
    image: kalilinux/kali-rolling
    container_name: kali
    networks:
      - private_network
    tty: true
    stdin_open: true

networks:
  private_network:
    driver: bridge

volumes:
  snort_data:
