# version: '3.8'

services:
  snort:
    build: 
      context: ./snort
      dockerfile: Dockerfile
    container_name: snort
    volumes:
      - ./snort/host-volume:/usr/local/snort/etc/snort/docker-volume:ro #rules 
    networks:
      - private_network
    stdin_open: true

  kali:
    image: kalilinux/kali-rolling
    container_name: kali
    networks:
      - private_network
    tty: true
    stdin_open: true

  web:
    image: bkimminich/juice-shop
    container_name: juice
    networks:
      - private_network
    volumes:
      - ./web/default.yml:/juice-shop/config/myConfig.yml
    restart: always

networks:
  private_network:
    driver: bridge


