
/home/maes/.nvm/versions/node/v22.11.0
/home/maes/.pyenv/shims:
/home/maes/.pyenv/plugins/pyenv-virtualenv/shims:
/home/maes/.local
/home/maes/.nvm/versions/node/v22.11.0
/home/maes/.pyenv/plugins/pyenv-virtualenv/shims:
/usr/local:
/usr:
/bin:
/usr/local/games:
/home/maes/sandbox/snort3/build/src/:
/sbin:
/bin/libwebp-1.4/bin/:
/shared/maes/appImages:
/home/maes/.pyenv
/usr/games:/home/maes/sandbox/snort3/build/src/:
/home/maes/scripts:
/usr/local/texlive/2024/bin/x86_64-linux/